webtalk_init -webtalk_dir C:/Users/federico/Desktop/embedded_systems_verilog_tutorials/wrapper/wrapper.sim/sim_1/behav/xsim/xsim.dir/range_reduction_tb2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May  4 00:08:02 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ecddd2a7-9cef-40dc-bec3-0f8f29ff5c52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e928d5556ab45a6b4cedf0e116f13af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "17" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "394 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "39 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "266" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "20" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "85728_KB" -context "xsim\\usage"
webtalk_transmit -clientid 116584010 -regid "" -xml C:/Users/federico/Desktop/embedded_systems_verilog_tutorials/wrapper/wrapper.sim/sim_1/behav/xsim/xsim.dir/range_reduction_tb2_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/federico/Desktop/embedded_systems_verilog_tutorials/wrapper/wrapper.sim/sim_1/behav/xsim/xsim.dir/range_reduction_tb2_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/federico/Desktop/embedded_systems_verilog_tutorials/wrapper/wrapper.sim/sim_1/behav/xsim/xsim.dir/range_reduction_tb2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
