webtalk_init -webtalk_dir C:/Coding_Projects/ES_project/TEST_BENCHES/Taylor_16_project/Taylor_16_project.sim/sim_1/behav/xsim/xsim.dir/TAYLOR_exp_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 22 17:48:20 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "514defd9-a463-49d7-8ef8-59012c4af0d6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9fd1b024c06d4733a7e0c243a867e668" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1155 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6124_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1073734598 -regid "" -xml C:/Coding_Projects/ES_project/TEST_BENCHES/Taylor_16_project/Taylor_16_project.sim/sim_1/behav/xsim/xsim.dir/TAYLOR_exp_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Coding_Projects/ES_project/TEST_BENCHES/Taylor_16_project/Taylor_16_project.sim/sim_1/behav/xsim/xsim.dir/TAYLOR_exp_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Coding_Projects/ES_project/TEST_BENCHES/Taylor_16_project/Taylor_16_project.sim/sim_1/behav/xsim/xsim.dir/TAYLOR_exp_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
